In [1]:
import pandas as pd

In [16]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?api_key=3be03d7c94c03ea51a93cf7d46661d07&language=en-US&page=1%27"

response = requests.get(url)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg","genre_ids":[18,80],"id":278,"original_language":"en","original_title":"The Shawshank Redemption","overview":"Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.","popularity":134.724,"poster_path":"/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg","release_date":"1994-09-23","title":"The Shawshank Redemption","video":false,"vote_average":8.71,"vote_count":25327},{"adult":false,"backdrop_path":"/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg","genre_ids":[18,80],"id":238,"original_language":"en","original_title":"The Godfather","overview":"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.","popularity":128.822,"poster_path":"/3bhkrj58Vtu7enYsRolD1fZdja1.jpg","release_date":"1972-03-14","title":"The Godfather","video":false,"vote_average":8.708,"vote_count":19293},{"adult":false,"backdrop_path":"/kGzFbGhp99zva6oZODW5atUtnqi.jpg","genre_ids":[18,80],"id":240,"original_language":"en","original_title":"The Godfather Part II","overview":"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.","popularity":84.795,"poster_path":"/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg","release_date":"1974-12-20","title":"The Godfather Part II","video":false,"vote_average":8.59,"vote_count":11636},{"adult":false,"backdrop_path":"/3f92DMBTFqr3wgXpfxzrb0qv8nG.jpg","genre_ids":[18,36,10752],"id":424,"original_language":"en","original_title":"Schindler's List","overview":"The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.","popularity":73.187,"poster_path":"/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg","release_date":"1993-12-15","title":"Schindler's List","video":false,"vote_average":8.572,"vote_count":14994},{"adult":false,"backdrop_path":"/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg","genre_ids":[35,18,10749],"id":19404,"original_language":"hi","original_title":"दिलवाले दुल्हनिया ले जायेंगे","overview":"Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.","popularity":34.162,"poster_path":"/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg","release_date":"1995-10-20","title":"Dilwale Dulhania Le Jayenge","video":false,"vote_average":8.547,"vote_count":4317},{"adult":false,"backdrop_path":"/qqHQsStV6exghCM7zbObuYBiYxw.jpg","genre_ids":[18],"id":389,"original_language":"en","original_title":"12 Angry Men","overview":"The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.","popularity":44.461,"poster_path":"/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg","release_date":"1957-04-10","title":"12 Angry Men","video":false,"vote_average":8.545,"vote_count":7946},{"adult":false,"backdrop_path":"/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg","genre_ids":[16,10751,14],"id":129,"original_language":"ja","original_title":"千と千尋の神隠し","overview":"A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.","popularity":110.264,"poster_path":"/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg","release_date":"2001-07-20","title":"Spirited Away","video":false,"vote_average":8.538,"vote_count":15372},{"adult":false,"backdrop_path":"/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg","genre_ids":[18,28,80,53],"id":155,"original_language":"en","original_title":"The Dark Knight","overview":"Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.","popularity":109.923,"poster_path":"/qJ2tW6WMUDux911r6m7haRef0WH.jpg","release_date":"2008-07-16","title":"The Dark Knight","video":false,"vote_average":8.514,"vote_count":31249},{"adult":false,"backdrop_path":"/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg","genre_ids":[35,53,18],"id":496243,"original_language":"ko","original_title":"기생충","overview":"All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.","popularity":91.838,"poster_path":"/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg","release_date":"2019-05-30","title":"Parasite","video":false,"vote_average":8.512,"vote_count":16937},{"adult":false,"backdrop_path":"/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg","genre_ids":[14,18,80],"id":497,"original_language":"en","original_title":"The Green Mile","overview":"A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.","popularity":74.166,"poster_path":"/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg","release_date":"1999-12-10","title":"The Green Mile","video":false,"vote_average":8.51,"vote_count":16360},{"adult":false,"backdrop_path":"/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg","genre_ids":[10749,16,18],"id":372058,"original_language":"ja","original_title":"君の名は。","overview":"High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.","popularity":81.067,"poster_path":"/q719jXXEzOoYaps6babgKnONONX.jpg","release_date":"2016-08-26","title":"Your Name.","video":false,"vote_average":8.498,"vote_count":10666},{"adult":false,"backdrop_path":"/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg","genre_ids":[53,80],"id":680,"original_language":"en","original_title":"Pulp Fiction","overview":"A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.","popularity":102.026,"poster_path":"/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg","release_date":"1994-09-10","title":"Pulp Fiction","video":false,"vote_average":8.489,"vote_count":26450},{"adult":false,"backdrop_path":"/qdIMHd4sEfJSckfVJfKQvisL02a.jpg","genre_ids":[35,18,10749],"id":13,"original_language":"en","original_title":"Forrest Gump","overview":"A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.","popularity":87.837,"poster_path":"/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg","release_date":"1994-06-23","title":"Forrest Gump","video":false,"vote_average":8.477,"vote_count":25991},{"adult":false,"backdrop_path":"/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg","genre_ids":[12,14,28],"id":122,"original_language":"en","original_title":"The Lord of the Rings: The Return of the King","overview":"Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.","popularity":103.343,"poster_path":"/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg","release_date":"2003-12-01","title":"The Lord of the Rings: The Return of the King","video":false,"vote_average":8.476,"vote_count":22856},{"adult":false,"backdrop_path":"/eoCSp75lxatmIa6aGqfnzwtbttd.jpg","genre_ids":[37],"id":429,"original_language":"it","original_title":"Il buono, il brutto, il cattivo","overview":"While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.","popularity":70.462,"poster_path":"/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg","release_date":"1966-12-22","title":"The Good, the Bad and the Ugly","video":false,"vote_average":8.471,"vote_count":8007},{"adult":false,"backdrop_path":"/sw7mordbZxgITU877yTpZCud90M.jpg","genre_ids":[18,80],"id":769,"original_language":"en","original_title":"GoodFellas","overview":"The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.","popularity":102.121,"poster_path":"/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg","release_date":"1990-09-12","title":"GoodFellas","video":false,"vote_average":8.466,"vote_count":12059},{"adult":false,"backdrop_path":"/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg","genre_ids":[28,18],"id":346,"original_language":"ja","original_title":"七人の侍","overview":"A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.","popularity":47.931,"poster_path":"/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg","release_date":"1954-04-26","title":"Seven Samurai","video":false,"vote_average":8.458,"vote_count":3357},{"adult":false,"backdrop_path":"/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg","genre_ids":[35,18],"id":637,"original_language":"it","original_title":"La vita è bella","overview":"A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.","popularity":62.978,"poster_path":"/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg","release_date":"1997-12-20","title":"Life Is Beautiful","video":false,"vote_average":8.456,"vote_count":12496},{"adult":false,"backdrop_path":"/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg","genre_ids":[16,18,10752],"id":12477,"original_language":"ja","original_title":"火垂るの墓","overview":"In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.","popularity":0.6,"poster_path":"/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg","release_date":"1988-04-15","title":"Grave of the Fireflies","video":false,"vote_average":8.5,"vote_count":5043},{"adult":false,"backdrop_path":"/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg","genre_ids":[18,10749],"id":11216,"original_language":"it","original_title":"Nuovo Cinema Paradiso","overview":"A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.","popularity":33.783,"poster_path":"/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg","release_date":"1988-11-17","title":"Cinema Paradiso","video":false,"vote_average":8.451,"vote_count":4077}],"total_pages":454,"total_results":9078}

In [17]:
response.json()["results"]

[{'adult': False,
  'backdrop_path': '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 134.724,
  'poster_path': '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.71,
  'vote_count': 25327},
 {'adult': False,
  'backdrop_path': '/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 128.822,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.708,
  'vote_count': 19293},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 84.795,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.59,
  'vote_count': 11636},
 {'adult': False,
  'backdrop_path': '/3f92DMBTFqr3wgXpfxzrb0qv8nG.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 73.187,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.572,
  'vote_count': 14994},
 {'adult': False,
  'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 34.162,
  'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
  'release_date': '1995-10-20',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.547,
  'vote_count': 4317},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 44.461,
  'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.545,
  'vote_count': 7946},
 {'adult': False,
  'backdrop_path': '/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 110.264,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.538,
  'vote_count': 15372},
 {'adult': False,
  'backdrop_path': '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
  'genre_ids': [18, 28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 109.923,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.514,
  'vote_count': 31249},
 {'adult': False,
  'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 91.838,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.512,
  'vote_count': 16937},
 {'adult': False,
  'backdrop_path': '/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 74.166,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.51,
  'vote_count': 16360},
 {'adult': False,
  'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
  'genre_ids': [10749, 16, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 81.067,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.498,
  'vote_count': 10666},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 102.026,
  'poster_path': '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.489,
  'vote_count': 26450},
 {'adult': False,
  'backdrop_path': '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 87.837,
  'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
  'release_date': '1994-06-23',
  'title': 'Forrest Gump',
  'video': False,
  'vote_average': 8.477,
  'vote_count': 25991},
 {'adult': False,
  'backdrop_path': '/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
  'popularity': 103.343,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-01',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.476,
  'vote_count': 22856},
 {'adult': False,
  'backdrop_path': '/eoCSp75lxatmIa6aGqfnzwtbttd.jpg',
  'genre_ids': [37],
  'id': 429,
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 70.462,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-22',
  'title': 'The Good, the Bad and the Ugly',
  'video': False,
  'vote_average': 8.471,
  'vote_count': 8007},
 {'adult': False,
  'backdrop_path': '/sw7mordbZxgITU877yTpZCud90M.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 102.121,
  'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
  'release_date': '1990-09-12',
  'title': 'GoodFellas',
  'video': False,
  'vote_average': 8.466,
  'vote_count': 12059},
 {'adult': False,
  'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
  'genre_ids': [28, 18],
  'id': 346,
  'original_language': 'ja',
  'original_title': '七人の侍',
  'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  'popularity': 47.931,
  'poster_path': '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
  'release_date': '1954-04-26',
  'title': 'Seven Samurai',
  'video': False,
  'vote_average': 8.458,
  'vote_count': 3357},
 {'adult': False,
  'backdrop_path': '/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg',
  'genre_ids': [35, 18],
  'id': 637,
  'original_language': 'it',
  'original_title': 'La vita è bella',
  'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
  'popularity': 62.978,
  'poster_path': '/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg',
  'release_date': '1997-12-20',
  'title': 'Life Is Beautiful',
  'video': False,
  'vote_average': 8.456,
  'vote_count': 12496},
 {'adult': False,
  'backdrop_path': '/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg',
  'genre_ids': [16, 18, 10752],
  'id': 12477,
  'original_language': 'ja',
  'original_title': '火垂るの墓',
  'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
  'popularity': 0.6,
  'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
  'release_date': '1988-04-15',
  'title': 'Grave of the Fireflies',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 5043},
 {'adult': False,
  'backdrop_path': '/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg',
  'genre_ids': [18, 10749],
  'id': 11216,
  'original_language': 'it',
  'original_title': 'Nuovo Cinema Paradiso',
  'overview': "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
  'popularity': 33.783,
  'poster_path': '/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg',
  'release_date': '1988-11-17',
  'title': 'Cinema Paradiso',
  'video': False,
  'vote_average': 8.451,
  'vote_count': 4077}]

In [18]:
pd.DataFrame(response.json()["results"])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg,"[18, 80]",278,en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,134.724,/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg,1994-09-23,The Shawshank Redemption,False,8.710,25327
1,False,/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",128.822,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.708,19293
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,84.795,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.590,11636
3,False,/3f92DMBTFqr3wgXpfxzrb0qv8nG.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,73.187,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.572,14994
4,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",34.162,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.547,4317
5,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,44.461,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.545,7946
6,False,/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",110.264,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.538,15372
7,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,109.923,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.514,31249
8,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",91.838,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.512,16937
9,False,/l6hQWH9eDksNJNiXWYRkWqikOdu.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,74.166,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.510,16360
10,False,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg,"[10749, 16, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,81.067,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.498,10666
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",102.026,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,1994-09-10,Pulp Fiction,False,8.489,26450
12,False,/qdIMHd4sEfJSckfVJfKQvisL02a.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,87.837,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.477,25991
13,False,/9DeGfFIqjph5CBFVQrD6wv9S7rR.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,103.343,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-01,The Lord of the Rings: The Return of the King,False,8.476,22856
14,False,/eoCSp75lxatmIa6aGqfnzwtbttd.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,70.462,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.471,8007
15,False,/sw7mordbZxgITU877yTpZCud90M.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",102.121,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.466,12059
16,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,47.931,/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg,1954-04-26,Seven Samurai,False,8.458,3357
17,False,/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,62.978,/6tEJnof1DKWPnl5lzkjf0FVv7oB.jpg,1997-12-20,Life Is Beautiful,False,8.456,12496
18,False,/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.600,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-15,Grave of the Fireflies,False,8.500,5043
19,False,/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg,"[18, 10749]",11216,it,Nuovo Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",33.783,/8SRUfRUi6x4O68n0VCbDNRa6iGL.jpg,1988-11-17,Cinema Paradiso,False,8.451,4077

In [19]:
df = pd.DataFrame(response.json()["results"])[["id", "title", "overview", "popularity", "release_date", "vote_average", "vote_count"]]

In [20]:
df.head()

,id,title,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,134.724,1994-09-23,8.710,25327
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",128.822,1972-03-14,8.708,19293
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,84.795,1974-12-20,8.590,11636
3,424,Schindler's List,The true story of how businessman Oskar Schind...,73.187,1993-12-15,8.572,14994
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",34.162,1995-10-20,8.547,4317

In [21]:
df1 = pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [25]:
for i in range(1, 455):
    requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=3be03d7c94c03ea51a93cf7d46661d07&language=en-US&page={}".format(i))
    temp_df = pd.DataFrame(response.json()["results"])[["id", "title", "overview", "popularity", "release_date", "vote_average", "vote_count"]]
    df1 = df1._append(temp_df, ignore_index=True)

In [36]:
df1.to_csv("movies.csv", index=False)

In [37]:
movies = pd.read_csv("movies.csv")

In [38]:
movies.shape

(9080, 7)

In [39]:
movies

,id,title,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,134.724,1994-09-23,8.710,25327
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",128.822,1972-03-14,8.708,19293
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,84.795,1974-12-20,8.590,11636
3,424,Schindler's List,The true story of how businessman Oskar Schind...,73.187,1993-12-15,8.572,14994
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",34.162,1995-10-20,8.547,4317
...,...,...,...,...,...,...,...
9075,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",102.121,1990-09-12,8.466,12059
9076,346,Seven Samurai,A samurai answers a village's request for prot...,47.931,1954-04-26,8.458,3357
9077,637,Life Is Beautiful,A touching story of an Italian book seller of ...,62.978,1997-12-20,8.456,12496
9078,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",0.600,1988-04-15,8.500,5043
9079,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",33.783,1988-11-17,8.451,4077

In [13]:
import requests

url = "https://free-nba.p.rapidapi.com/players"

querystring = {"page":"0","per_page":"25"}

headers = {
	"X-RapidAPI-Key": "8628bf8a66msh65401b0d048f118p13ed56jsn7adef0368a0a",
	"X-RapidAPI-Host": "free-nba.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'data': [{'id': 14, 'first_name': 'Ike', 'height_feet': None, 'height_inches': None, 'last_name': 'Anigbogu', 'position': 'C', 'team': {'id': 12, 'abbreviation': 'IND', 'city': 'Indiana', 'conference': 'East', 'division': 'Central', 'full_name': 'Indiana Pacers', 'name': 'Pacers'}, 'weight_pounds': None}, {'id': 25, 'first_name': 'Ron', 'height_feet': None, 'height_inches': None, 'last_name': 'Baker', 'position': 'G', 'team': {'id': 20, 'abbreviation': 'NYK', 'city': 'New York', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'New York Knicks', 'name': 'Knicks'}, 'weight_pounds': None}, {'id': 47, 'first_name': 'Jabari', 'height_feet': None, 'height_inches': None, 'last_name': 'Bird', 'position': 'G', 'team': {'id': 2, 'abbreviation': 'BOS', 'city': 'Boston', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'Boston Celtics', 'name': 'Celtics'}, 'weight_pounds': None}, {'id': 67, 'first_name': 'MarShon', 'height_feet': None, 'height_inches': None, 'last_name': 'Brooks', 'position': 'G', 'team': {'id': 15, 'abbreviation': 'MEM', 'city': 'Memphis', 'conference': 'West', 'division': 'Southwest', 'full_name': 'Memphis Grizzlies', 'name': 'Grizzlies'}, 'weight_pounds': None}, {'id': 71, 'first_name': 'Lorenzo', 'height_feet': None, 'height_inches': None, 'last_name': 'Brown', 'position': 'G', 'team': {'id': 28, 'abbreviation': 'TOR', 'city': 'Toronto', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'Toronto Raptors', 'name': 'Raptors'}, 'weight_pounds': None}, {'id': 90, 'first_name': 'Omri', 'height_feet': None, 'height_inches': None, 'last_name': 'Casspi', 'position': 'F', 'team': {'id': 15, 'abbreviation': 'MEM', 'city': 'Memphis', 'conference': 'West', 'division': 'Southwest', 'full_name': 'Memphis Grizzlies', 'name': 'Grizzlies'}, 'weight_pounds': None}, {'id': 1, 'first_name': 'Alex', 'height_feet': 6, 'height_inches': 6, 'last_name': 'Abrines', 'position': 'G', 'team': {'id': 21, 'abbreviation': 'OKC', 'city': 'Oklahoma City', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Oklahoma City Thunder', 'name': 'Thunder'}, 'weight_pounds': 200}, {'id': 119, 'first_name': 'Tyler', 'height_feet': None, 'height_inches': None, 'last_name': 'Davis', 'position': 'C', 'team': {'id': 21, 'abbreviation': 'OKC', 'city': 'Oklahoma City', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Oklahoma City Thunder', 'name': 'Thunder'}, 'weight_pounds': None}, {'id': 149, 'first_name': 'Keenan', 'height_feet': None, 'height_inches': None, 'last_name': 'Evans', 'position': 'G', 'team': {'id': 9, 'abbreviation': 'DET', 'city': 'Detroit', 'conference': 'East', 'division': 'Central', 'full_name': 'Detroit Pistons', 'name': 'Pistons'}, 'weight_pounds': None}, {'id': 179, 'first_name': 'Marcin', 'height_feet': None, 'height_inches': None, 'last_name': 'Gortat', 'position': 'C', 'team': {'id': 13, 'abbreviation': 'LAC', 'city': 'LA', 'conference': 'West', 'division': 'Pacific', 'full_name': 'LA Clippers', 'name': 'Clippers'}, 'weight_pounds': None}, {'id': 1593, 'first_name': 'Andrew', 'height_feet': None, 'height_inches': None, 'last_name': 'Bogut', 'position': 'F', 'team': {'id': 10, 'abbreviation': 'GSW', 'city': 'Golden State', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Golden State Warriors', 'name': 'Warriors'}, 'weight_pounds': None}, {'id': 241, 'first_name': 'Amir', 'height_feet': 6, 'height_inches': 9, 'last_name': 'Johnson', 'position': 'C-F', 'team': {'id': 23, 'abbreviation': 'PHI', 'city': 'Philadelphia', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'Philadelphia 76ers', 'name': '76ers'}, 'weight_pounds': 240}, {'id': 392, 'first_name': 'Malachi', 'height_feet': None, 'height_inches': None, 'last_name': 'Richardson', 'position': 'G', 'team': {'id': 29, 'abbreviation': 'UTA', 'city': 'Utah', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Utah Jazz', 'name': 'Jazz'}, 'weight_pounds': None}, {'id': 281, 'first_name': 'Zach', 'height_feet': None, 'height_inches': None, 'last_name': 'Lofton', 'position': 'G', 'team': {'id': 9, 'abbreviation': 'DET', 'city': 'Detroit', 'conference': 'East', 'division': 'Central', 'full_name': 'Detroit Pistons', 'name': 'Pistons'}, 'weight_pounds': None}, {'id': 263, 'first_name': 'Kosta', 'height_feet': 7, 'height_inches': 0, 'last_name': 'Koufos', 'position': 'C', 'team': {'id': 26, 'abbreviation': 'SAC', 'city': 'Sacramento', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Sacramento Kings', 'name': 'Kings'}, 'weight_pounds': 245}, {'id': 382, 'first_name': 'Billy', 'height_feet': None, 'height_inches': None, 'last_name': 'Preston', 'position': 'F', 'team': {'id': 6, 'abbreviation': 'CLE', 'city': 'Cleveland', 'conference': 'East', 'division': 'Central', 'full_name': 'Cleveland Cavaliers', 'name': 'Cavaliers'}, 'weight_pounds': None}, {'id': 384, 'first_name': 'Zhou', 'height_feet': None, 'height_inches': None, 'last_name': 'Qi', 'position': 'F-C', 'team': {'id': 11, 'abbreviation': 'HOU', 'city': 'Houston', 'conference': 'West', 'division': 'Southwest', 'full_name': 'Houston Rockets', 'name': 'Rockets'}, 'weight_pounds': None}, {'id': 388, 'first_name': 'Zach', 'height_feet': None, 'height_inches': None, 'last_name': 'Randolph', 'position': 'F', 'team': {'id': 26, 'abbreviation': 'SAC', 'city': 'Sacramento', 'conference': 'West', 'division': 'Pacific', 'full_name': 'Sacramento Kings', 'name': 'Kings'}, 'weight_pounds': None}, {'id': 430, 'first_name': 'DJ', 'height_feet': None, 'height_inches': None, 'last_name': 'Stephens', 'position': 'G-F', 'team': {'id': 15, 'abbreviation': 'MEM', 'city': 'Memphis', 'conference': 'West', 'division': 'Southwest', 'full_name': 'Memphis Grizzlies', 'name': 'Grizzlies'}, 'weight_pounds': None}, {'id': 437, 'first_name': 'Milos', 'height_feet': None, 'height_inches': None, 'last_name': 'Teodosic', 'position': 'G', 'team': {'id': 13, 'abbreviation': 'LAC', 'city': 'LA', 'conference': 'West', 'division': 'Pacific', 'full_name': 'LA Clippers', 'name': 'Clippers'}, 'weight_pounds': None}, {'id': 448, 'first_name': 'Gary', 'height_feet': None, 'height_inches': None, 'last_name': 'Trent Jr.', 'position': 'G', 'team': {'id': 25, 'abbreviation': 'POR', 'city': 'Portland', 'conference': 'West', 'division': 'Northwest', 'full_name': 'Portland Trail Blazers', 'name': 'Trail Blazers'}, 'weight_pounds': None}, {'id': 494, 'first_name': 'Michael', 'height_feet': None, 'height_inches': None, 'last_name': 'Smith', 'position': '', 'team': {'id': 2, 'abbreviation': 'BOS', 'city': 'Boston', 'conference': 'East', 'division': 'Atlantic', 'full_name': 'Boston Celtics', 'name': 'Celtics'}, 'weight_pounds': None}, {'id': 495, 'first_name': 'John', 'height_feet': None, 'height_inches': None, 'last_name': 'Morton', 'position': '', 'team': {'id': 6, 'abbreviation': 'CLE', 'city': 'Cleveland', 'conference': 'East', 'division': 'Central', 'full_name': 'Cleveland Cavaliers', 'name': 'Cavaliers'}, 'weight_pounds': None}, {'id': 496, 'first_name': 'Howard', 'height_feet': None, 'height_inches': None, 'last_name': 'Wright', 'position': '', 'team': {'id': 1, 'abbreviation': 'ATL', 'city': 'Atlanta', 'conference': 'East', 'division': 'Southeast', 'full_name': 'Atlanta Hawks', 'name': 'Hawks'}, 'weight_pounds': None}, {'id': 497, 'first_name': 'Michael', 'height_feet': None, 'height_inches': None, 'last_name': 'Ansley', 'position': '', 'team': {'id': 22, 'abbreviation': 'ORL', 'city': 'Orlando', 'conference': 'East', 'division': 'Southeast', 'full_name': 'Orlando Magic', 'name': 'Magic'}, 'weight_pounds': None}], 'meta': {'total_pages': 209, 'current_page': 1, 'next_page': 2, 'per_page': 25, 'total_count': 5207}}

In [15]:
response.json()["data"]

[{'id': 14,
  'first_name': 'Ike',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Anigbogu',
  'position': 'C',
  'team': {'id': 12,
   'abbreviation': 'IND',
   'city': 'Indiana',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Indiana Pacers',
   'name': 'Pacers'},
  'weight_pounds': None},
 {'id': 25,
  'first_name': 'Ron',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Baker',
  'position': 'G',
  'team': {'id': 20,
   'abbreviation': 'NYK',
   'city': 'New York',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'New York Knicks',
   'name': 'Knicks'},
  'weight_pounds': None},
 {'id': 47,
  'first_name': 'Jabari',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Bird',
  'position': 'G',
  'team': {'id': 2,
   'abbreviation': 'BOS',
   'city': 'Boston',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'Boston Celtics',
   'name': 'Celtics'},
  'weight_pounds': None},
 {'id': 67,
  'first_name': 'MarShon',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Brooks',
  'position': 'G',
  'team': {'id': 15,
   'abbreviation': 'MEM',
   'city': 'Memphis',
   'conference': 'West',
   'division': 'Southwest',
   'full_name': 'Memphis Grizzlies',
   'name': 'Grizzlies'},
  'weight_pounds': None},
 {'id': 71,
  'first_name': 'Lorenzo',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Brown',
  'position': 'G',
  'team': {'id': 28,
   'abbreviation': 'TOR',
   'city': 'Toronto',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'Toronto Raptors',
   'name': 'Raptors'},
  'weight_pounds': None},
 {'id': 90,
  'first_name': 'Omri',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Casspi',
  'position': 'F',
  'team': {'id': 15,
   'abbreviation': 'MEM',
   'city': 'Memphis',
   'conference': 'West',
   'division': 'Southwest',
   'full_name': 'Memphis Grizzlies',
   'name': 'Grizzlies'},
  'weight_pounds': None},
 {'id': 1,
  'first_name': 'Alex',
  'height_feet': 6,
  'height_inches': 6,
  'last_name': 'Abrines',
  'position': 'G',
  'team': {'id': 21,
   'abbreviation': 'OKC',
   'city': 'Oklahoma City',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Oklahoma City Thunder',
   'name': 'Thunder'},
  'weight_pounds': 200},
 {'id': 119,
  'first_name': 'Tyler',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Davis',
  'position': 'C',
  'team': {'id': 21,
   'abbreviation': 'OKC',
   'city': 'Oklahoma City',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Oklahoma City Thunder',
   'name': 'Thunder'},
  'weight_pounds': None},
 {'id': 149,
  'first_name': 'Keenan',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Evans',
  'position': 'G',
  'team': {'id': 9,
   'abbreviation': 'DET',
   'city': 'Detroit',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Detroit Pistons',
   'name': 'Pistons'},
  'weight_pounds': None},
 {'id': 179,
  'first_name': 'Marcin',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Gortat',
  'position': 'C',
  'team': {'id': 13,
   'abbreviation': 'LAC',
   'city': 'LA',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'LA Clippers',
   'name': 'Clippers'},
  'weight_pounds': None},
 {'id': 1593,
  'first_name': 'Andrew',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Bogut',
  'position': 'F',
  'team': {'id': 10,
   'abbreviation': 'GSW',
   'city': 'Golden State',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Golden State Warriors',
   'name': 'Warriors'},
  'weight_pounds': None},
 {'id': 241,
  'first_name': 'Amir',
  'height_feet': 6,
  'height_inches': 9,
  'last_name': 'Johnson',
  'position': 'C-F',
  'team': {'id': 23,
   'abbreviation': 'PHI',
   'city': 'Philadelphia',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'Philadelphia 76ers',
   'name': '76ers'},
  'weight_pounds': 240},
 {'id': 392,
  'first_name': 'Malachi',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Richardson',
  'position': 'G',
  'team': {'id': 29,
   'abbreviation': 'UTA',
   'city': 'Utah',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Utah Jazz',
   'name': 'Jazz'},
  'weight_pounds': None},
 {'id': 281,
  'first_name': 'Zach',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Lofton',
  'position': 'G',
  'team': {'id': 9,
   'abbreviation': 'DET',
   'city': 'Detroit',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Detroit Pistons',
   'name': 'Pistons'},
  'weight_pounds': None},
 {'id': 263,
  'first_name': 'Kosta',
  'height_feet': 7,
  'height_inches': 0,
  'last_name': 'Koufos',
  'position': 'C',
  'team': {'id': 26,
   'abbreviation': 'SAC',
   'city': 'Sacramento',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Sacramento Kings',
   'name': 'Kings'},
  'weight_pounds': 245},
 {'id': 382,
  'first_name': 'Billy',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Preston',
  'position': 'F',
  'team': {'id': 6,
   'abbreviation': 'CLE',
   'city': 'Cleveland',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Cleveland Cavaliers',
   'name': 'Cavaliers'},
  'weight_pounds': None},
 {'id': 384,
  'first_name': 'Zhou',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Qi',
  'position': 'F-C',
  'team': {'id': 11,
   'abbreviation': 'HOU',
   'city': 'Houston',
   'conference': 'West',
   'division': 'Southwest',
   'full_name': 'Houston Rockets',
   'name': 'Rockets'},
  'weight_pounds': None},
 {'id': 388,
  'first_name': 'Zach',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Randolph',
  'position': 'F',
  'team': {'id': 26,
   'abbreviation': 'SAC',
   'city': 'Sacramento',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'Sacramento Kings',
   'name': 'Kings'},
  'weight_pounds': None},
 {'id': 430,
  'first_name': 'DJ',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Stephens',
  'position': 'G-F',
  'team': {'id': 15,
   'abbreviation': 'MEM',
   'city': 'Memphis',
   'conference': 'West',
   'division': 'Southwest',
   'full_name': 'Memphis Grizzlies',
   'name': 'Grizzlies'},
  'weight_pounds': None},
 {'id': 437,
  'first_name': 'Milos',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Teodosic',
  'position': 'G',
  'team': {'id': 13,
   'abbreviation': 'LAC',
   'city': 'LA',
   'conference': 'West',
   'division': 'Pacific',
   'full_name': 'LA Clippers',
   'name': 'Clippers'},
  'weight_pounds': None},
 {'id': 448,
  'first_name': 'Gary',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Trent Jr.',
  'position': 'G',
  'team': {'id': 25,
   'abbreviation': 'POR',
   'city': 'Portland',
   'conference': 'West',
   'division': 'Northwest',
   'full_name': 'Portland Trail Blazers',
   'name': 'Trail Blazers'},
  'weight_pounds': None},
 {'id': 494,
  'first_name': 'Michael',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Smith',
  'position': '',
  'team': {'id': 2,
   'abbreviation': 'BOS',
   'city': 'Boston',
   'conference': 'East',
   'division': 'Atlantic',
   'full_name': 'Boston Celtics',
   'name': 'Celtics'},
  'weight_pounds': None},
 {'id': 495,
  'first_name': 'John',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Morton',
  'position': '',
  'team': {'id': 6,
   'abbreviation': 'CLE',
   'city': 'Cleveland',
   'conference': 'East',
   'division': 'Central',
   'full_name': 'Cleveland Cavaliers',
   'name': 'Cavaliers'},
  'weight_pounds': None},
 {'id': 496,
  'first_name': 'Howard',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Wright',
  'position': '',
  'team': {'id': 1,
   'abbreviation': 'ATL',
   'city': 'Atlanta',
   'conference': 'East',
   'division': 'Southeast',
   'full_name': 'Atlanta Hawks',
   'name': 'Hawks'},
  'weight_pounds': None},
 {'id': 497,
  'first_name': 'Michael',
  'height_feet': None,
  'height_inches': None,
  'last_name': 'Ansley',
  'position': '',
  'team': {'id': 22,
   'abbreviation': 'ORL',
   'city': 'Orlando',
   'conference': 'East',
   'division': 'Southeast',
   'full_name': 'Orlando Magic',
   'name': 'Magic'},
  'weight_pounds': None}]

In [21]:
df2 = pd.DataFrame(response.json()["data"])

In [22]:
df2.to_csv("nba.csv",index = False)

In [23]:
pd.read_csv("nba.csv")

,id,first_name,height_feet,height_inches,last_name,position,team,weight_pounds
0,14,Ike,NaN,NaN,Anigbogu,C,"{'id': 12, 'abbreviation': 'IND', 'city': 'Ind...",NaN
1,25,Ron,NaN,NaN,Baker,G,"{'id': 20, 'abbreviation': 'NYK', 'city': 'New...",NaN
2,47,Jabari,NaN,NaN,Bird,G,"{'id': 2, 'abbreviation': 'BOS', 'city': 'Bost...",NaN
3,67,MarShon,NaN,NaN,Brooks,G,"{'id': 15, 'abbreviation': 'MEM', 'city': 'Mem...",NaN
4,71,Lorenzo,NaN,NaN,Brown,G,"{'id': 28, 'abbreviation': 'TOR', 'city': 'Tor...",NaN
5,90,Omri,NaN,NaN,Casspi,F,"{'id': 15, 'abbreviation': 'MEM', 'city': 'Mem...",NaN
6,1,Alex,6.0,6.0,Abrines,G,"{'id': 21, 'abbreviation': 'OKC', 'city': 'Okl...",200.0
7,119,Tyler,NaN,NaN,Davis,C,"{'id': 21, 'abbreviation': 'OKC', 'city': 'Okl...",NaN
8,149,Keenan,NaN,NaN,Evans,G,"{'id': 9, 'abbreviation': 'DET', 'city': 'Detr...",NaN
9,179,Marcin,NaN,NaN,Gortat,C,"{'id': 13, 'abbreviation': 'LAC', 'city': 'LA'...",NaN
10,1593,Andrew,NaN,NaN,Bogut,F,"{'id': 10, 'abbreviation': 'GSW', 'city': 'Gol...",NaN
11,241,Amir,6.0,9.0,Johnson,C-F,"{'id': 23, 'abbreviation': 'PHI', 'city': 'Phi...",240.0
12,392,Malachi,NaN,NaN,Richardson,G,"{'id': 29, 'abbreviation': 'UTA', 'city': 'Uta...",NaN
13,281,Zach,NaN,NaN,Lofton,G,"{'id': 9, 'abbreviation': 'DET', 'city': 'Detr...",NaN
14,263,Kosta,7.0,0.0,Koufos,C,"{'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...",245.0
15,382,Billy,NaN,NaN,Preston,F,"{'id': 6, 'abbreviation': 'CLE', 'city': 'Clev...",NaN
16,384,Zhou,NaN,NaN,Qi,F-C,"{'id': 11, 'abbreviation': 'HOU', 'city': 'Hou...",NaN
17,388,Zach,NaN,NaN,Randolph,F,"{'id': 26, 'abbreviation': 'SAC', 'city': 'Sac...",NaN
18,430,DJ,NaN,NaN,Stephens,G-F,"{'id': 15, 'abbreviation': 'MEM', 'city': 'Mem...",NaN
19,437,Milos,NaN,NaN,Teodosic,G,"{'id': 13, 'abbreviation': 'LAC', 'city': 'LA'...",NaN
20,448,Gary,NaN,NaN,Trent Jr.,G,"{'id': 25, 'abbreviation': 'POR', 'city': 'Por...",NaN
21,494,Michael,NaN,NaN,Smith,NaN,"{'id': 2, 'abbreviation': 'BOS', 'city': 'Bost...",NaN
22,495,John,NaN,NaN,Morton,NaN,"{'id': 6, 'abbreviation': 'CLE', 'city': 'Clev...",NaN
23,496,Howard,NaN,NaN,Wright,NaN,"{'id': 1, 'abbreviation': 'ATL', 'city': 'Atla...",NaN
24,497,Michael,NaN,NaN,Ansley,NaN,"{'id': 22, 'abbreviation': 'ORL', 'city': 'Orl...",NaN

In [24]:
df3 = pd.DataFrame()
df3

Empty DataFrame
Columns: []
Index: []

In [25]:
for i in range(1, 26):
    url = "https://free-nba.p.rapidapi.com/players"

    querystring = {"page":{}.format(i),"per_page":"25"}

    headers = {
    	"X-RapidAPI-Key": "8628bf8a66msh65401b0d048f118p13ed56jsn7adef0368a0a",
    	"X-RapidAPI-Host": "free-nba.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers, params=querystring)
    temp_df = pd.DataFrame(response.json()["data"])
    df3 = df3._append(temp_df, ignore_index=True)

AttributeError: 'dict' object has no attribute 'format'